# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 9.0

background_opacity 0.95

# black
color0  #10100E
color8  #696969

# red
color1  #C40233
color9  #FF2400

# green
color2  #009F6B
color10 #03C03C

# yellow
color3  #FFD700
color11 #FDFF00

# blue
color4  #0087BD
color12 #007FFF

# magenta
color5  #9A4EAE
color13 #FF1493

# cyan
color6  #20B2AA
color14 #00CCCC

# white
color7  #C6C6C4
color15 #FFFAFA


scrollback_pager nvim -u NONE 
    \ -c "set nonumber nolist showtabline=0 foldcolumn=0 clipboard=unnamedplus" 
    \ -c "map q :q<CR>"
    \ -c "autocmd TermOpen * normal G" 
    \ -c "silent write! /tmp/kitty_scrollback_buffer | te cat /tmp/kitty_scrollback_buffer - "
