#!/bin/bash

function ing1-lab() {
    tmux new-session -d -s ing1-lab -n "editor"

    tmux send-keys -t ing1-lab:editor "cd ~/Documents/FAMAF/ingenieria-software-1/frontend/" Enter
    tmux send-keys -t ing1-lab:editor "clear" Enter

    tmux new-window -t ing1-lab -n "server"
    tmux send-keys -t ing1-lab:server "cd ~/Documents/FAMAF/ingenieria-software-1/frontend/" Enter
    tmux send-keys -t ing1-lab:server "clear" Enter

    tmux split-window -v -t ing1-lab:server
    tmux send-keys -t ing1-lab:server.1 "cd ~/Documents/FAMAF/ingenieria-software-1/backend/" Enter
    tmux send-keys -t ing1-lab:server.1 "clear" Enter
}

AVAILABLE_SESSIONS=(ing1-lab)

if [[ " ${AVAILABLE_SESSIONS[*]} " =~ [[:space:]]$1[[:space:]] ]]; then
    tmux has-session -t $1  2> /dev/null

    if [[ $? == 1 ]]; then
        $1
    fi

    tmux attach-session -t $1
else
    echo -n "Available sessions are: "
    echo ${AVAILABLE_SESSIONS[*]} | sed "s/\([A-Za-z0-9-]\) \([A-Za-z0-9-]\)/\1, \2/g"
fi
